spring:
  application:
    name: order_service
  datasource:
    url: jdbc:postgresql://localhost:5432/ecommerce_orders
    username: dev
    password: dev
  jpa:
    hibernate:
      ddl-auto: update

server:
  port: 8082

services:
  product:
    url:  http://localhost:8081

management:
  endpoints:
    web:
      exposure:
        include:  health, info, metrics